/* ==========================================================================
 * font-stroke-flow app: UI wiring + live Lottie preview
 * ========================================================================== */
"use strict";

const $ = (id) => document.getElementById(id);

const state = {
  mode: "brush",              // "brush" | "outline" | "stroke"
  brushScale: 130,            // brush width as % of the letter's own thickness
  lineSpacing: 125,           // line height as % of font size
  text: "Hello",
  outlineFontKey: "poppins",  // "poppins" | "pacifico" | "custom"
  customFont: null,           // parsed opentype font
  customFontName: "",
  hersheyId: "scriptc",
  easing: "ease-in-out",
  letterDuration: 0.8,
  overlap: 60,
  timingMode: "uniform",
  holdSeconds: 0.5,
  fps: 60,
  strokeColor: "#111111",
  fillColor: "#111111",
  strokeWidth: 5,
  fontSize: 220,
  fillMode: "fade",
  fillStart: 55,
  fillDuration: 60,
  bgMode: "transparent",
  bgColor: "#ffffff",
};

const fonts = { poppins: null, pacifico: null }; // parsed opentype fonts
let hersheyData = null;
let anim = null;
let currentDoc = null;
let playing = true;
let scrubbing = false;

/* ---------------- assets ---------------- */
async function loadAssets() {
  const [pop, pac, her] = await Promise.all([
    fetch("fonts/Poppins-SemiBold.ttf").then((r) => r.arrayBuffer()),
    fetch("fonts/Pacifico-Regular.ttf").then((r) => r.arrayBuffer()),
    fetch("data/hersheytext.min.json").then((r) => r.json()),
  ]);
  fonts.poppins = opentype.parse(pop);
  fonts.pacifico = opentype.parse(pac);
  hersheyData = her;
}

function activeOutlineFont() {
  if (state.outlineFontKey === "custom" && state.customFont) return state.customFont;
  return fonts[state.outlineFontKey] || fonts.poppins;
}

/* the style picker demos itself: each card loops its own word, written in
 * its own style, generated by the same engine as the real output */
function buildModePreviews() {
  const params = (mode) => ({
    mode, fps: 30, letterDuration: 0.5, overlap: 70, easing: "ease-in-out",
    timingMode: "natural", strokeColor: "#1d1b26", strokeWidth: 3.5,
    fillColor: "#1d1b26", fillMode: "fade", fillStart: 55, fillDuration: 60,
    brushScale: 130, holdSeconds: 1.1, bgColor: null, name: `demo-${mode}`,
  });
  const SIZE = 90, PAD = 14;
  const extract = {
    brush: () => extractBrushLetters(fonts.poppins, "Brush", SIZE, PAD),
    outline: () => extractOutlineLetters(fonts.poppins, "Outline", SIZE, PAD),
    stroke: () => extractHersheyLetters(hersheyData.scriptc, "Pen", SIZE, PAD),
  };
  document.querySelectorAll(".mode-mini").forEach((box) => {
    const mode = box.dataset.mini;
    try {
      const doc = buildLottie(params(mode), extract[mode]());
      lottie.loadAnimation({
        container: box, renderer: "svg", loop: true, autoplay: true,
        animationData: doc,
      });
    } catch (err) {
      console.error(`mode preview '${mode}' failed`, err);
      box.textContent = { brush: "🖌 Brush", outline: "Outline", stroke: "Pen" }[mode];
    }
  });
}

/* ---------------- build + preview ---------------- */
function rebuild() {
  if (!hersheyData || !fonts.poppins) return;

  const pad = state.fontSize * 0.15 + state.strokeWidth;
  const lineHeight = state.fontSize * (state.lineSpacing / 100);
  let extracted;
  if (state.mode === "outline") {
    extracted = extractOutlineLetters(activeOutlineFont(), state.text, state.fontSize, pad, lineHeight);
  } else if (state.mode === "brush") {
    extracted = extractBrushLetters(activeOutlineFont(), state.text, state.fontSize, pad, lineHeight);
  } else {
    extracted = extractHersheyLetters(hersheyData[state.hersheyId], state.text, state.fontSize, pad, lineHeight);
  }

  const warn = $("missing-warn");
  if (extracted.missing.length) {
    warn.hidden = false;
    warn.textContent = `⚠ not in this font, skipped: ${[...new Set(extracted.missing)].join(" ")}`;
  } else warn.hidden = true;

  currentDoc = buildLottie(
    {
      mode: state.mode,
      fps: state.fps,
      letterDuration: state.letterDuration,
      overlap: state.overlap,
      easing: state.easing,
      timingMode: state.timingMode,
      strokeColor: state.strokeColor,
      strokeWidth: state.strokeWidth,
      fillColor: state.fillColor,
      fillMode: state.fillMode,
      fillStart: state.fillStart,
      fillDuration: state.fillDuration,
      brushScale: state.brushScale,
      holdSeconds: state.holdSeconds,
      bgColor: state.bgMode === "color" ? state.bgColor : null,
      name: `font-stroke-flow: ${state.text}`,
    },
    extracted
  );

  // (re)load the player — lottie mutates the object, so hand it a copy
  const speed = anim ? anim.playSpeed : 1;
  if (anim) anim.destroy();
  anim = lottie.loadAnimation({
    container: $("lottie-box"),
    renderer: "svg",
    loop: $("loop").checked,
    autoplay: true,
    animationData: JSON.parse(JSON.stringify(currentDoc)),
  });
  anim.setSpeed(speed);
  playing = true;
  $("btn-play").textContent = "⏸";

  anim.addEventListener("enterFrame", () => {
    if (scrubbing) return;
    const f = anim.currentFrame;
    $("scrub").value = f;
    $("time-label").textContent =
      `${(f / currentDoc.fr).toFixed(1)} / ${(currentDoc.op / currentDoc.fr).toFixed(1)}s`;
  });
  anim.addEventListener("complete", () => {
    if (!$("loop").checked) { playing = false; $("btn-play").textContent = "▶"; }
  });

  $("scrub").max = Math.max(1, currentDoc.op - 1);
  const secs = (currentDoc.op / currentDoc.fr).toFixed(1);
  const kb = (JSON.stringify(currentDoc).length / 1024).toFixed(1);
  $("file-info").textContent =
    `${currentDoc.w} × ${currentDoc.h}px · ${secs}s @ ${currentDoc.fr}fps · ` +
    `${currentDoc.layers.length} layers · ~${kb} KB`;
}

let rebuildTimer = null;
function scheduleRebuild(delay = 160) {
  clearTimeout(rebuildTimer);
  rebuildTimer = setTimeout(rebuild, delay);
}

/* ---------------- control bindings ---------------- */
function bindSlider(id, outId, key, fmt, isFloat = true) {
  const input = $(id);
  const parse = (s) => (isFloat ? parseFloat(s) : parseInt(s, 10));
  const def = parse(input.getAttribute("value")); // the authored default

  // DaVinci-style back-to-default dot, appears when the value moves
  const dot = document.createElement("button");
  dot.type = "button";
  dot.className = "reset-dot";
  dot.title = "reset to default";
  input.closest(".field").querySelector("label").appendChild(dot);
  const refreshDot = (v) => dot.classList.toggle("visible", v !== def);

  input.addEventListener("input", (e) => {
    const v = parse(e.target.value);
    state[key] = v;
    $(outId).textContent = fmt(v);
    refreshDot(v);
    scheduleRebuild();
  });
  dot.addEventListener("click", () => {
    input.value = def;
    state[key] = def;
    $(outId).textContent = fmt(def);
    refreshDot(def);
    scheduleRebuild();
  });
}

function bindSeg(segId, key, onChange) {
  const seg = $(segId);
  seg.querySelectorAll(".seg-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      seg.querySelectorAll(".seg-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      state[key] = btn.dataset.val;
      if (onChange) onChange(btn.dataset.val);
      scheduleRebuild();
    });
  });
}

function setupControls() {
  // mode
  const MODE_HINTS = {
    brush: "painted with real brush strokes through each letter — works with any font",
    outline: "traces each letter's outline, then fills it in",
    stroke: "single-line pen writing (Hershey engraving fonts)",
  };
  const applyModeVisibility = () => {
    const m = state.mode;
    const usesRealFont = m === "brush" || m === "outline";
    $("mode-hint").textContent = MODE_HINTS[m];
    $("outline-font-row").hidden = !usesRealFont;
    $("stroke-font-row").hidden = usesRealFont;
    $("fill-controls").style.display = m === "outline" ? "" : "none";
    $("fill-color-field").style.display = m !== "stroke" ? "" : "none";
    $("stroke-width-field").style.display = m !== "brush" ? "" : "none";
    $("stroke-color-field").style.display = m !== "brush" ? "" : "none";
    $("brush-size-field").style.display = m === "brush" ? "" : "none";
  };
  document.querySelectorAll(".mode-btn").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".mode-btn").forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      state.mode = btn.dataset.mode;
      applyModeVisibility();
      scheduleRebuild();
    });
  });
  applyModeVisibility();

  $("text-input").addEventListener("input", (e) => {
    state.text = e.target.value;
    scheduleRebuild(250);
  });

  $("font-select").addEventListener("change", (e) => {
    state.outlineFontKey = e.target.value;
    scheduleRebuild();
  });
  $("hershey-select").addEventListener("change", (e) => {
    state.hersheyId = e.target.value;
    scheduleRebuild();
  });
  // easing select + live demo dot
  const updateEaseDemo = () => {
    const [x1, y1, x2, y2] = EASINGS[state.easing] || EASINGS["ease-in-out"];
    const dot = $("ease-dot");
    dot.style.animation = "none";
    void dot.offsetWidth; // restart the loop so the change is felt immediately
    dot.style.animation = "";
    dot.style.animationTimingFunction = `cubic-bezier(${x1},${y1},${x2},${y2})`;
  };
  $("easing").addEventListener("change", (e) => {
    state.easing = e.target.value;
    updateEaseDemo();
    scheduleRebuild();
  });
  updateEaseDemo();
  $("fps").addEventListener("change", (e) => {
    state.fps = parseInt(e.target.value, 10);
    scheduleRebuild();
  });

  bindSlider("letter-duration", "out-duration", "letterDuration", (v) => `${v}s`);
  bindSlider("overlap", "out-overlap", "overlap", (v) => `${v}%`, false);
  bindSlider("hold", "out-hold", "holdSeconds", (v) => `${v}s`);
  bindSlider("stroke-width", "out-strokew", "strokeWidth", (v) => `${v}`);
  bindSlider("font-size", "out-fontsize", "fontSize", (v) => `${v}`, false);
  bindSlider("fill-start", "out-fillstart", "fillStart", (v) => `${v}%`, false);
  bindSlider("fill-duration", "out-filldur", "fillDuration", (v) => `${v}%`, false);
  bindSlider("brush-size", "out-brushsize", "brushScale", (v) => `${v}%`, false);
  bindSlider("line-spacing", "out-linespacing", "lineSpacing", (v) => `${v}%`, false);

  bindSeg("timing-seg", "timingMode");
  bindSeg("fill-seg", "fillMode", (v) => {
    $("fill-timing").style.display = v === "fade" ? "" : "none";
  });
  bindSeg("bg-seg", "bgMode", (v) => {
    $("bg-color").hidden = v !== "color";
    $("stage").classList.toggle("checker", v !== "color");
  });

  $("stroke-color").addEventListener("input", (e) => { state.strokeColor = e.target.value; scheduleRebuild(); });
  $("fill-color").addEventListener("input", (e) => { state.fillColor = e.target.value; scheduleRebuild(); });
  $("bg-color").addEventListener("input", (e) => { state.bgColor = e.target.value; scheduleRebuild(); });

  // custom font upload
  const loadFontFile = async (file) => {
    try {
      const buf = await file.arrayBuffer();
      state.customFont = opentype.parse(buf);
      state.customFontName = file.name;
      const sel = $("font-select");
      let opt = sel.querySelector('option[value="custom"]');
      if (!opt) {
        opt = document.createElement("option");
        opt.value = "custom";
        sel.appendChild(opt);
      }
      opt.textContent = `${file.name} (uploaded)`;
      sel.value = "custom";
      state.outlineFontKey = "custom";
      scheduleRebuild();
    } catch (err) {
      alert(`Could not read that font: ${err.message}`);
    }
  };

  $("browse-btn").addEventListener("click", () => $("font-file").click());
  $("font-file").addEventListener("change", (e) => {
    if (e.target.files[0]) loadFontFile(e.target.files[0]);
  });
  const dz = $("dropzone");
  ["dragenter", "dragover"].forEach((ev) =>
    dz.addEventListener(ev, (e) => { e.preventDefault(); dz.classList.add("dragover"); }));
  ["dragleave", "drop"].forEach((ev) =>
    dz.addEventListener(ev, (e) => { e.preventDefault(); dz.classList.remove("dragover"); }));
  dz.addEventListener("drop", (e) => {
    if (e.dataTransfer.files[0]) loadFontFile(e.dataTransfer.files[0]);
  });

  // player
  $("btn-play").addEventListener("click", () => {
    if (!anim) return;
    playing = !playing;
    playing ? anim.play() : anim.pause();
    $("btn-play").textContent = playing ? "⏸" : "▶";
  });
  $("btn-restart").addEventListener("click", () => {
    if (!anim) return;
    anim.goToAndPlay(0, true);
    playing = true;
    $("btn-play").textContent = "⏸";
  });
  $("scrub").addEventListener("pointerdown", () => { scrubbing = true; if (anim) anim.pause(); });
  $("scrub").addEventListener("input", (e) => {
    if (anim) anim.goToAndStop(parseFloat(e.target.value), true);
  });
  $("scrub").addEventListener("pointerup", () => {
    scrubbing = false;
    if (anim && playing) anim.play();
  });
  $("loop").addEventListener("change", (e) => { if (anim) anim.loop = e.target.checked; });
  $("speed").addEventListener("input", (e) => {
    const v = parseFloat(e.target.value);
    if (anim) anim.setSpeed(v);
    $("speed-label").textContent = `${v}×`;
  });

  // export — one place for every format
  const safeName = () =>
    (state.text.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "animation");
  const saveBlob = (blob, filename) => {
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const EXPORT_HINTS = {
    lottie: "tiny vector file — After Effects, web, iOS & Android Lottie players",
    mp4: "H.264 video on a background color (your Background color, or white)",
    gif: "animated GIF (~30fps) on a background color",
    webm: "VP9 video that keeps transparency (Chrome) — for overlaying in edits",
  };
  const updateExportUI = () => {
    const f = $("export-format").value;
    $("export-scale").hidden = f === "lottie";
    $("btn-copy").hidden = f !== "lottie";
    $("export-hint").textContent = EXPORT_HINTS[f];
  };
  if (!mp4Supported())
    $("export-format").querySelector('option[value="mp4"]').disabled = true;
  $("export-format").addEventListener("change", updateExportUI);
  updateExportUI();

  $("btn-copy").addEventListener("click", async () => {
    if (!currentDoc) return;
    await navigator.clipboard.writeText(JSON.stringify(currentDoc));
    const btn = $("btn-copy");
    const old = btn.textContent;
    btn.textContent = "✓ Copied";
    setTimeout(() => (btn.textContent = old), 1200);
  });

  $("btn-export").addEventListener("click", async () => {
    if (!currentDoc) return;
    const format = $("export-format").value;
    const status = $("export-status");

    if (format === "lottie") {
      const blob = new Blob([JSON.stringify(currentDoc)], { type: "application/json" });
      saveBlob(blob, `${safeName()}-lottie.json`);
      status.textContent = `✓ saved ${(blob.size / 1024).toFixed(0)} KB Lottie`;
      return;
    }

    const scale = parseFloat($("export-scale").value);
    const btn = $("btn-export");
    const bar = $("export-bar");
    btn.disabled = true;
    $("export-progress").classList.add("active");
    status.textContent = format === "webm"
      ? "recording in real time…" : "rendering frames…";
    try {
      const bgColor =
        state.bgMode === "color" ? state.bgColor
        : format === "webm" ? null           // keep transparency
        : "#ffffff";
      const { blob, ext } = await exportAnimation({
        doc: currentDoc, format, scale, bgColor,
        onProgress: (p) => { bar.style.width = `${Math.round(p * 100)}%`; },
      });
      bar.style.width = "100%";
      saveBlob(blob, `${safeName()}.${ext}`);
      status.textContent = `✓ exported ${(blob.size / 1048576).toFixed(1)} MB ${ext.toUpperCase()}`;
    } catch (err) {
      console.error(err);
      status.textContent = `⚠ export failed: ${err.message || err}`;
    } finally {
      btn.disabled = false;
      setTimeout(() => {
        $("export-progress").classList.remove("active");
        bar.style.width = "0%";
      }, 1500);
    }
  });
}

/* ---------------- boot ---------------- */
(async function init() {
  setupControls();
  try {
    await loadAssets();
  } catch (err) {
    $("file-info").textContent =
      "⚠ Could not load bundled assets — serve this folder over HTTP (e.g. `npx serve`).";
    console.error(err);
    return;
  }
  buildModePreviews();
  rebuild();
})();
